export const vehicleTypes = [
  {
    id: 'bike',
    name: 'Bike',
    icon: 'bicycle',
    baseFare: 20,
    perKmRate: 8,
    perMinuteRate: 1,
    capacity: 1,
    image: 'bike',
  },
  {
    id: 'auto',
    name: 'Auto',
    icon: 'car-sport',
    baseFare: 30,
    perKmRate: 12,
    perMinuteRate: 1.5,
    capacity: 3,
    image: 'auto',
  },
  {
    id: 'economy',
    name: 'Economy',
    icon: 'car',
    baseFare: 50,
    perKmRate: 15,
    perMinuteRate: 2,
    capacity: 4,
    image: 'economy',
  },
  {
    id: 'premium',
    name: 'Premium',
    icon: 'car-sport',
    baseFare: 80,
    perKmRate: 25,
    perMinuteRate: 3,
    capacity: 4,
    image: 'premium',
  },
];